in_channels: 3
num_classes: 100
depth_multiple: 1.0
width_multiple: 1.0

layers:
- [ -1, 1, ConvBlock, 64, 3, 2, { drop: 0.1 } ]
- [ -1, 1, ConvBlock, 128, 3, 2, { act: relu, norm: ln } ]
- [ -1, 1, TransformerEncoderBlock, 128, 4, 8 ]
- [ -1, 1, ConvBlock, 256, 3, 2 ]
- [ -1, 1, GlobalAvgPool ]
- [ -1, 1, LinearBlock, 1024, silu ]
- [ -1, 1, LinearBlock, num_classes ]
