in_channels: 3
num_classes: 20
depth_multiple: 1.0
width_multiple: 1.0

layers:
- [ -1, 2, ConvBlock, 64, 3, 2, { drop: 0.1, act: relu } ]
- [ -1, 2, ConvBlock, 128, 3, 2, { act: relu } ]
- [ -1, 1, ConvBlock, 256, 3, 2, { drop: 0.1, act: relu, norm: ln } ]
- [ -1, 1, TransformerEncoderBlock, 256, 4, 8, { drop: 0.1, act: silu, norm: ln } ]
- [ -1, 2, ConvBlock, 256, 1, 1, { drop: 0.1 } ]
- [ -1, 1, GlobalAvgPool ]
- [ -1, 1, LinearBlock, 1024, silu ]
- [ -1, 1, LinearBlock, num_classes ]
