# VGG16 Model Configuration
# 간소화된 VGG16 모델 (MNIST 데이터에 최적화)

# 기본 설정
in_channels: 1  # MNIST 이미지는 흑백 1채널
num_classes: 10  # MNIST 클래스 수
input_size: [28, 28]  # MNIST 이미지 크기

# 스케일링 factor (더 작은 모델로 조정)
depth_multiple: 1.0
width_multiple: 0.5  # 원래 VGG16보다 더 작은 채널 수 사용

# 레이어 정의 [from, number, block_type, out_channels, kernel_size, stride, {params}]
# from: -1은 이전 레이어, 숫자는 해당 인덱스의 레이어 출력 사용
layers:
  # Block 1
  - [-1, 1, ConvBlock, 64, 3, 1, {act: relu, norm: bn}]   # Conv1_1
  - [-1, 1, ConvBlock, 64, 3, 1, {act: relu, norm: bn}]   # Conv1_2
  - [-1, 1, ConvBlock, 64, 2, 2, {act: relu}]             # MaxPool1 (stride=2로 다운샘플링)

  # Block 2
  - [-1, 1, ConvBlock, 128, 3, 1, {act: relu, norm: bn}]  # Conv2_1
  - [-1, 1, ConvBlock, 128, 3, 1, {act: relu, norm: bn}]  # Conv2_2
  - [-1, 1, ConvBlock, 128, 2, 2, {act: relu}]            # MaxPool2 (stride=2로 다운샘플링)

  # Block 3
  - [-1, 1, ConvBlock, 256, 3, 1, {act: relu, norm: bn}]  # Conv3_1
  - [-1, 1, ConvBlock, 256, 3, 1, {act: relu, norm: bn}]  # Conv3_2
  - [-1, 1, ConvBlock, 256, 3, 1, {act: relu, norm: bn}]  # Conv3_3
  - [-1, 1, ConvBlock, 256, 2, 2, {act: relu}]            # MaxPool3 (stride=2로 다운샘플링)

  # 특성 평탄화 (Flatten)
  - [-1, 1, GlobalAvgPool, 0]                           # 전역 평균 풀링으로 차원 감소

  # 완전 연결 레이어 (FC)
  - [-1, 1, LinearBlock, 512, {act: relu, drop: 0.5}]   # FC1
  - [-1, 1, LinearBlock, 512, {act: relu, drop: 0.5}]   # FC2
  - [-1, 1, LinearBlock, 10, {}]                        # 출력 레이어(softmax는 외부에서)
